# Generated by Django 5.0 on 2024-02-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_status', '0002_taskstatusmodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstatusmodel',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
