name: Main CI

on:
  push:
    branches: ["main"]

jobs:
  buid:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-in-project: true
    - name: Build project
      run: |
        make build
    - name: Lint
      run: make lint
    - name: Test
      run: make test