name: main CI

on:
  push:
    branches:
      - "main"

jobs:
  buid:
    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Build project
      run: |
        make install
        make build
    - name: Lint
      run: make lint
    - name: Test
      env:
        - SECRET_KEY: "1234"
        - DEBUG: "True"
      run: make test