name: Main CI

on:
  push:
    branches: ["main"]

jobs:
  buid:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        make install
    - name: Build project
      run: |
        poetry run python manage.py collectstatic --no-input
        poetry run python manage.py migrate
    - name: Lint
      run: make lint
    - name: Test coverage
    - uses: paambaati/codeclimate-action@v5
      env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          SECRET_KEY: "1234"
      with:
        coverageCommand: make test-coverage
        debug: true
